testing update

diff --git a/deploy-agent-conf b/deploy-agent-conf
--- a/deploy-agent-conf
+++ b/deploy-agent-conf
@@ -3,28 +3,27 @@
 # It doesn't matter where the script is executed from, it's always as if we are invoking it from script's directory
 parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
 cd "$parent_path"
-
-zbx_restart_flag=0
+zbx_restart_flag=0;
 
 # Compare returns 0 if files are the same, so we skip install and reset if it's unecessary
 echo "-----"
-echo "Installing scripts...";
+echo "Installing config files...";
 echo ""
 
-for file in ../$1/scripts/*; do
+for file in $1/agent/*.conf; do
 	current_file="${file##*/}";
 	echo "Installing $current_file...";
 
-	echo "Checking if script exists and / or needs to be updated...";
-	if ! cmp -s ../$1/scripts/$current_file /usr/local/bin/$current_file; then
+	echo "Checking if file exists and / or needs to be updated...";
+	if ! cmp -s $1/agent/$current_file /etc/zabbix/zabbix_agentd.d/$current_file; then
 		echo "Files are not the same!";
-		echo "Installing / Updating the script..."
+		echo "Installing / Updating file...";
 
-		if install -D --owner root --group zabbix -m 750 ../$1/scripts/$current_file /usr/local/bin/$current_file; then
-			echo "Script updated successfully!";
+		if install -D --owner root --group zabbix -m 740 $1/agent/$current_file               /etc/zabbix/zabbix_agentd.d/$current_file; then
+			echo "File updated successfully!";
 			zbx_restart_flag=1;
 		else
-			echo "Failed to update the script";
+			echo "Failed to update the file";
 		fi
 		
 	else
@@ -36,12 +35,14 @@ done;
 
 if [[ $zbx_restart_flag -ne 0 ]]; then
 	echo "Restarting zabbix-agent.service..."
+
 	if systemctl restart zabbix-agent.service; then
 		echo "Zabbix service restarted successfully!";
 	else
 		echo "Zabbix service failed to restart.";
 	fi
 fi
+
 
 echo "Done!"
 echo "Exiting program..."
